name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROXY_FUNCTION_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase functions deploy height_task_create_github_issue --project-ref $PROJECT_ID
      - run: supabase functions deploy height_task_update_github_issue --project-ref $PROJECT_ID
      - run: supabase functions deploy height_task_droped_github_issue --project-ref $PROJECT_ID
      - run: supabase functions deploy height_alarm_to_slack --project-ref $PROJECT_ID
      - run: supabase functions deploy github_branch_alarm_to_slack --project-ref $PROJECT_ID
      - run: supabase functions deploy github_pr_alarm_to_slack --project-ref $PROJECT_ID
      - run: supabase functions deploy github_deploy_alarm_to_slack --project-ref $PROJECT_ID
      - run: supabase functions deploy radiojocky --project-ref $PROJECT_ID